### PR TITLE
autostart cmst a little bit delayed to prevent bugs with systray

### PR DESCRIPTION
**Pull request by agaida**
i know there are things like X-GNOME-Autostart-Delay:10 or X-LXQt-Need-Tray=true  - but there is no common thing for all desktops

### CODE REVIEW

**Comment by andrew-bibb** [comment]
Actually this feature is already built in using the -w (--wait-time) command line argument.  If you think we really need this I'd prefer the .desktop file to start this way: "cmst --wait-time 5", or "cmst -w 5").  

There are actually a bunch of trays I've run across where we have to force a wait.  5 seconds usually is enough, but I recall one where the user had to use 10.

**Comment by agaida** [comment]
ok - didn't see the -w switch, my bad - and yes, we should set this one, i usually autostart cmst minimized and encounter problems with the systray nearly every boot without waiting. So a delay of 5 secs don't hurt i think.

**Comment by agaida** [comment]
@andrew-bibb changed the pull request, -w5 works like charm, thank you

**Comment by andrew-bibb** [comment]
Thanks.
I'll do the pull sometime over the weekend.  I'm hot and heavy in the adding the VPN functionality and I've got 2 local branches going at the moment.  I can do the pull here, but I've found I've got to make sure I've got no outstanding commits from my local branches or it just becomes a mess.  I'm sure there are commands to do all of it, but my GIT fluency is very elementary,

**Pull request merged**
