### PR TITLE
User proper categories to show cmst in the system setting menu

### PR DESCRIPTION
**Pull request by agaida**
BTW - why two desktop files, one should be enough?

### CODE REVIEW

**Comment by andrew-bibb** [comment]
One desktop file I created to be placed in /usr/share/applications.  That is the one that normally shows up in menus. 

The autostart one was the result of a pull request where someone wanted an entry to put into a users autostart folder.  It is placed there automatically if one checks enable autostart in the preferences tab (he wrote that code as well).

There are (or were) subtle differences between the two.

I'm going to pull these into our devel branch to give me a chance to look them over in detail.  If you are looking for them that is where they are.

**Comment by agaida** [comment]
i understand the reasons - but see no blocker to use the standard one for autostart - hmm, maybe i miss something but normally™ it should work that way

**Comment by andrew-bibb** [comment]
The way the autostart code was written if the user happens to overwrite or change the one in his local autostart directory then CMST will revert it back next time the program is started.  I actually had to ask the submitter before I did the PR because I was not clear on that. I know what it is doing, but not why it might be important.  I couldn't see any harm in it though, so I let it in.  

The only one that can be edited by a user, and have the edits stick, is the one in /usr/share/applications.

I don't actually use either on my system (I've a pretty minimal setup), and I probably should pay a bit more attention to what they are and what they are doing.

**Comment by agaida** [comment]
ok - i understand it now. Only a thought - a normal user should not change things in /usr/share/applications nor in and other directory what need admin rights (ok, theory :) ) So if one want permanent changes one should make a copy himself like 

cp /usr/share/applications/cmst.desktop $HOME/.config/autostart/mycmst.desktop or
cp /usr/share/applications/cmst.desktop /etc/xdg/autostart/mycmst.desktop

At least the package maintainer should be able to do so - but maybe i'm a little bit old fashiond in these things.

**Pull request merged**
